FROM node:latest
MAINTAINER Microsoft Healthcare Bot Team

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

ENV WEBCHAT_SECRET=bpohlVbrmQU.bY3OGraRJC8f9zGcpsNhez-dPw4RgqOwr6VuSpJh3Ko
ENV APP_SECRET=u_uTB~d0.f6eVG2-0oxU.nGA6Vfwavou3D

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

# Delete the web.config file, only needed for IIS
RUN rm ./Web.config

EXPOSE 8080
CMD [ "npm", "start" ]
