# INSTALL PYTHON IMAGE
FROM iyappan24/ubuntupy

# INSTALL TOOLS
RUN apt-get update \
    && apt-get -y install unzip \
    && apt-get -y install libaio-dev


RUN mkdir backend

COPY . / /backend/

WORKDIR /backend

RUN pip3 install -r requirements.txt
RUN pip3 install -e .

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "src.app"]
